export const PLANOS = [
  {
    id: 'TRIAL' as const,
    nome: 'Trial',
    preco: 0,
    periodo: '14 dias grátis',
    descricao: 'Para experimentar sem compromisso',
    stripePriceId: null as string | null,
    destaque: false,
    features: [
      '1 profissional',
      'Até 30 atendimentos/mês',
      'Notificações WhatsApp',
      'Todos os tipos de serviço',
      'Suporte por e-mail',
    ],
    limitacoes: ['Sem upload de fotos/vídeos', 'Sem relatórios'],
    cta: 'Começar grátis',
    ctaHref: '/register' as string | null,
  },
  {
    id: 'BASICO' as const,
    nome: 'Básico',
    preco: 7900,
    periodo: '/mês',
    descricao: 'Para petshops e clínicas pequenas',
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_BASICO ?? '',
    destaque: false,
    features: [
      'Até 3 profissionais',
      'Até 200 atendimentos/mês',
      'Notificações WhatsApp',
      'Todos os tipos de serviço',
      'Upload de fotos nos estágios',
      'Histórico de atendimentos',
      'Suporte por e-mail',
    ],
    limitacoes: [],
    cta: 'Assinar Básico',
    ctaHref: null as string | null,
  },
  {
    id: 'PROFISSIONAL' as const,
    nome: 'Profissional',
    preco: 14900,
    periodo: '/mês',
    descricao: 'Para clínicas em crescimento',
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PROFISSIONAL ?? '',
    destaque: true,
    features: [
      'Até 10 profissionais',
      'Atendimentos ilimitados',
      'Notificações WhatsApp',
      'Todos os tipos de serviço',
      'Upload de fotos e vídeos',
      'Histórico completo',
      'Relatórios básicos',
      'Suporte prioritário',
    ],
    limitacoes: [],
    cta: 'Assinar Profissional',
    ctaHref: null as string | null,
  },
  {
    id: 'PREMIUM' as const,
    nome: 'Premium',
    preco: 29900,
    periodo: '/mês',
    descricao: 'Para redes e clínicas de alto volume',
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PREMIUM ?? '',
    destaque: false,
    features: [
      'Profissionais ilimitados',
      'Atendimentos ilimitados',
      'Notificações WhatsApp',
      'Todos os tipos de serviço',
      'Upload de fotos e vídeos',
      'Histórico completo',
      'Relatórios avançados',
      'Multi-unidade (em breve)',
      'Suporte dedicado via WhatsApp',
      'Onboarding personalizado',
    ],
    limitacoes: [],
    cta: 'Assinar Premium',
    ctaHref: null as string | null,
  },
];
