export const PLANOS = [
  {
    id: 'TRIAL' as const,
    nome: 'Starter',
    preco: 0,
    periodo: '7 dias grátis',
    descricao: 'Teste sem compromisso, sem cartão',
    stripePriceId: null as string | null,
    destaque: false,
    features: [
      '1 profissional',
      'Até 30 atendimentos',
      'Notificações WhatsApp',
      'Todos os tipos de serviço',
      'Suporte por e-mail',
    ],
    limitacoes: ['Sem upload de fotos/vídeos', 'Sem relatórios'],
    cta: 'Começar grátis',
    ctaHref: '/register' as string | null,
  },
  {
    id: 'PROFISSIONAL' as const,
    nome: 'Profissional',
    preco: 39700,
    periodo: '/mês',
    descricao: 'Para clínicas e petshops que levam o atendimento a sério',
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_PROFISSIONAL ?? '',
    destaque: true,
    features: [
      'Profissionais ilimitados',
      'Atendimentos ilimitados',
      'Notificações WhatsApp',
      'Todos os tipos de serviço',
      'Upload de fotos e vídeos nos estágios',
      'Histórico completo de atendimentos',
      'Relatórios de desempenho',
      'Suporte prioritário',
    ],
    limitacoes: [],
    cta: 'Assinar agora',
    ctaHref: null as string | null,
  },
  {
    id: 'ENTERPRISE' as const,
    nome: 'Enterprise',
    preco: -1, // sem preço fixo
    periodo: '',
    descricao: 'Para redes, hospitais veterinários e alto volume',
    stripePriceId: null as string | null,
    destaque: false,
    features: [
      'Tudo do Profissional',
      'Multi-unidade',
      'SLA 99% garantido em contrato',
      'CSM dedicado',
      'Onboarding e treinamento da equipe',
      'Integrações customizadas',
      'Faturamento por nota fiscal',
      'Contrato anual com desconto',
    ],
    limitacoes: [],
    cta: 'Falar com vendas',
    ctaHref: 'https://wa.me/5511999999999?text=Olá%2C%20quero%20saber%20mais%20sobre%20o%20plano%20Enterprise%20do%20VetTrack' as string | null,
  },
];
